### ISSUE TITLE
Cross compiled version for 2.12 doesn't seem to be published

### ISSUE THREAD

**Issue by gavares** [DefinitelyScala/scala-js-materialdesignlite#1]
After commit f5894b7, I can't seem to locate a 2.12 build for scala-js-materialdesignlite in jcenter repo:

http://jcenter.bintray.com/com/definitelyscala/

Wondering if there is another place to look for this artifact or if the publish failed.

**Comment by KyleU** [comment]
I had no idea folks were making issues for this stuff, sorry for the delay. I've published 2.12 artifacts for all the projects, thanks.
